export enum CheeseColors {
  gray = "Gray",
  lightgray = "Lightgray",
  blue = "Blue",
  lightblue = "Lightblue",
  cyan = "Cyan",
  lightcyan = "Lightcyan",
  red = "Red",
  lightred = "Lightred",
  green = "Green",
  lightgreen = "Lightgreen",
  yellow = "Yellow",
  lightyellow = "Lightyellow",
  magenta = "Magenta",
  lightmagenta = "Lightmagenta",
  black = "Black",
  white = "White",
}
